---
title: "edu-cost"
author: "Jake Weinreb"
date: "5/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = "/Users/jakeweinreb/Desktop/R/Data/Education/")
```

```{r libraries}
library(tidyverse)
library(janitor)
library(readr)
library(rebus)
```

## Distance Education and Retention Rates

```{r upload}
institution <- read_csv("institution.csv") %>% clean_names() %>% filter(instcat_hd2017 == 2)
retention_raw <- read_csv("retention.csv") %>% clean_names() %>% select(-x33) %>% 
  filter(unit_id %in% institution$unit_id) %>% 
  gather(key = full_year, value = full, contains("ret_pcf_ef")) %>% 
  gather(key = part_year, value = part, contains("ret_pcp_ef")) %>% 
  gather(key = exclusive_year, value = exclusive, contains("pctdeexc_drvef")) %>% 
  gather(key = some_year, value = some, contains("pctdesom_drvef")) %>% 
  gather(key = none_year, value = none, contains("pctdenon_drvef")) %>% 
  mutate(full_year = str_extract(full_year, "201" %R% DGT),
         part_year = str_extract(part_year, "201" %R% DGT),
         exclusive_year = str_extract(exclusive_year, "201" %R% DGT),
         some_year = str_extract(some_year, "201" %R% DGT),
         none_year = str_extract(none_year, "201" %R% DGT)) %>% #takes a while (~10 mins)
  filter(full_year == part_year, part_year == exclusive_year, exclusive_year == some_year, some_year == none_year)
```

```{r remote_over_time}
online_over_time <- retention_raw %>% select(full_year, exclusive, some, none) %>% group_by(full_year) %>%
  summarize(avg_exclusive = mean(exclusive, na.rm = TRUE),
            avg_some = mean(some, na.rm = TRUE),
            avg_none = mean(none, na.rm = TRUE)) %>% 
  gather(key = cat, value = avg, -full_year) 

online_over_time %>% ggplot(aes(full_year, avg, color = cat, group = cat)) + geom_point() + geom_line()
```

```{r num_remote}
num_remote <- retention_raw %>% select(full_year, exclusive, none) %>% 
  filter(exclusive == 100 | none == 100) %>% 
  gather(key = cat, value = pct, -full_year) %>% 
  filter(pct == 100) %>% 
  group_by(full_year, cat) %>% 
  tally()

num_remote %>% ggplot(aes(full_year, n, fill = cat)) + geom_col(position = 'dodge')
```

```{r comparison_over_time}
retention_raw %>% ggplot(aes(x = full, y = none, group = full_year)) + geom_point(alpha = .3) + facet_wrap(~full_year)
```

##Financial Statements

```{r financials_import}
for_profit <- rbind(read_csv("finance_profit_current"), read_csv("finance_profit_historical")) %>% clean_names() %>% filter(unit_id %in% institution$unit_id)
private <- rbind(read_csv("finance_private_current"), read_csv("finance_private_current")) %>% clean_names() %>% filter(unit_id %in% institution$unit_id)
public <- rbind(read_csv("finance_public_current"), read_csv("finance_public_historical1"), read_csv("finance_public_historical2")) %>% clean_names() %>% filter(unit_id %in% institution$unit_id)
```

ko

